/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tiflink.demo;

public class DemoFlinkJob {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
