/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tiflink.examples;
import org.tiflink.client.KVClient;

public class DemoFlinkJob {
    public static void main(String[] args) {
        KVClient client = new KVClient();
        System.out.println("Hello World!");
        client.test();
    }
}
